//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 12/27/2018 3:47:29 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Reflection;
using System.Linq.Expressions;
using System.Data.Entity.Core;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata


#endregion

namespace CCSpecialModel
{

    #region CCSpecialEntities

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CCSpecialEntities : ObjectContext
    {
        #region Constructors

        /// <summary>
        /// Initialize a new CCSpecialEntities object.
        /// </summary>
        public CCSpecialEntities() : 
                base(@"name=CCSpecialEntitiesConnectionString", "CCSpecialEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initializes a new CCSpecialEntities object using the connection string found in the 'CCSpecialEntities' section of the application configuration file.
        /// </summary>
        public CCSpecialEntities(string connectionString) : 
                base(connectionString, "CCSpecialEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initialize a new CCSpecialEntities object.
        /// </summary>
        public CCSpecialEntities(EntityConnection connection) : base(connection, "CCSpecialEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        #endregion

        #region Partial Methods

        partial void OnContextCreated();

        #endregion

        #region ObjectSet Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ecolabpo> Ecolabpos
        {
            get
            {
                if ((_Ecolabpos == null))
                {
                    _Ecolabpos = base.CreateObjectSet<Ecolabpo>("Ecolabpos");
                }
                return _Ecolabpos;
            }
        }
        private ObjectSet<Ecolabpo> _Ecolabpos;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PurchaseOrderMaster> PurchaseOrderMasters
        {
            get
            {
                if ((_PurchaseOrderMasters == null))
                {
                    _PurchaseOrderMasters = base.CreateObjectSet<PurchaseOrderMaster>("PurchaseOrderMasters");
                }
                return _PurchaseOrderMasters;
            }
        }
        private ObjectSet<PurchaseOrderMaster> _PurchaseOrderMasters;

        #endregion
        #region AddTo Methods

        /// <summary>
        /// Deprecated Method for adding a new object to the Ecolabpos EntitySet.
        /// </summary>
        public void AddToEcolabpos(Ecolabpo ecolabpo)
        {
            base.AddObject("Ecolabpos", ecolabpo);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the PurchaseOrderMasters EntitySet.
        /// </summary>
        public void AddToPurchaseOrderMasters(PurchaseOrderMaster purchaseOrderMaster)
        {
            base.AddObject("PurchaseOrderMasters", purchaseOrderMaster);
        }

        #endregion
    }

    #endregion
}

namespace CCSpecialModel
{

    /// <summary>
    /// There are no comments for CCSpecialModel.Ecolabpo in the schema.
    /// </summary>
    /// <KeyProperties>
    /// EcolabposID
    /// </KeyProperties>
    [EdmEntityTypeAttribute(NamespaceName="CCSpecialModel", Name="Ecolabpo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ecolabpo : EntityObject    {
        #region Factory Method

        /// <summary>
        /// Create a new Ecolabpo object.
        /// </summary>
        /// <param name="ecolabposID">Initial value of EcolabposID.</param>
        public static Ecolabpo CreateEcolabpo(string ecolabposID)
        {
            Ecolabpo ecolabpo = new Ecolabpo();
            ecolabpo.EcolabposID = ecolabposID;
            return ecolabpo;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for EcolabposID in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public virtual string EcolabposID
        {
            get
            {
                string value = _EcolabposID;
                OnGetEcolabposID(ref value);
                return value;
            }
            set
            {
                if (_EcolabposID != value)
                {
                  OnEcolabposIDChanging(ref value);
                  ReportPropertyChanging("EcolabposID");
                  _EcolabposID = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("EcolabposID");
                  OnEcolabposIDChanged();
              }
            }
        }
        private string _EcolabposID;
        partial void OnGetEcolabposID(ref string value);
        partial void OnEcolabposIDChanging(ref string value);
        partial void OnEcolabposIDChanged();
    
        /// <summary>
        /// There are no comments for PO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string PO
        {
            get
            {
                string value = _PO;
                OnGetPO(ref value);
                return value;
            }
            set
            {
                if (_PO != value)
                {
                  OnPOChanging(ref value);
                  ReportPropertyChanging("PO");
                  _PO = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("PO");
                  OnPOChanged();
              }
            }
        }
        private string _PO;
        partial void OnGetPO(ref string value);
        partial void OnPOChanging(ref string value);
        partial void OnPOChanged();
    
        /// <summary>
        /// There are no comments for PODATE in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual global::System.Nullable<System.DateTime> PODATE
        {
            get
            {
                global::System.Nullable<System.DateTime> value = _PODATE;
                OnGetPODATE(ref value);
                return value;
            }
            set
            {
                if (_PODATE != value)
                {
                  OnPODATEChanging(ref value);
                  ReportPropertyChanging("PODATE");
                  _PODATE = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("PODATE");
                  OnPODATEChanged();
              }
            }
        }
        private global::System.Nullable<System.DateTime> _PODATE;
        partial void OnGetPODATE(ref global::System.Nullable<System.DateTime> value);
        partial void OnPODATEChanging(ref global::System.Nullable<System.DateTime> value);
        partial void OnPODATEChanged();
    
        /// <summary>
        /// There are no comments for POLINE in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual global::System.Nullable<decimal> POLINE
        {
            get
            {
                global::System.Nullable<decimal> value = _POLINE;
                OnGetPOLINE(ref value);
                return value;
            }
            set
            {
                if (_POLINE != value)
                {
                  OnPOLINEChanging(ref value);
                  ReportPropertyChanging("POLINE");
                  _POLINE = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("POLINE");
                  OnPOLINEChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _POLINE;
        partial void OnGetPOLINE(ref global::System.Nullable<decimal> value);
        partial void OnPOLINEChanging(ref global::System.Nullable<decimal> value);
        partial void OnPOLINEChanged();
    
        /// <summary>
        /// There are no comments for PART in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual global::System.Nullable<decimal> PART
        {
            get
            {
                global::System.Nullable<decimal> value = _PART;
                OnGetPART(ref value);
                return value;
            }
            set
            {
                if (_PART != value)
                {
                  OnPARTChanging(ref value);
                  ReportPropertyChanging("PART");
                  _PART = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("PART");
                  OnPARTChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _PART;
        partial void OnGetPART(ref global::System.Nullable<decimal> value);
        partial void OnPARTChanging(ref global::System.Nullable<decimal> value);
        partial void OnPARTChanged();
    
        /// <summary>
        /// There are no comments for QTYDUE in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual global::System.Nullable<decimal> QTYDUE
        {
            get
            {
                global::System.Nullable<decimal> value = _QTYDUE;
                OnGetQTYDUE(ref value);
                return value;
            }
            set
            {
                if (_QTYDUE != value)
                {
                  OnQTYDUEChanging(ref value);
                  ReportPropertyChanging("QTYDUE");
                  _QTYDUE = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("QTYDUE");
                  OnQTYDUEChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _QTYDUE;
        partial void OnGetQTYDUE(ref global::System.Nullable<decimal> value);
        partial void OnQTYDUEChanging(ref global::System.Nullable<decimal> value);
        partial void OnQTYDUEChanged();
    
        /// <summary>
        /// There are no comments for DETAILS in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string DETAILS
        {
            get
            {
                string value = _DETAILS;
                OnGetDETAILS(ref value);
                return value;
            }
            set
            {
                if (_DETAILS != value)
                {
                  OnDETAILSChanging(ref value);
                  ReportPropertyChanging("DETAILS");
                  _DETAILS = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("DETAILS");
                  OnDETAILSChanged();
              }
            }
        }
        private string _DETAILS;
        partial void OnGetDETAILS(ref string value);
        partial void OnDETAILSChanging(ref string value);
        partial void OnDETAILSChanged();
    
        /// <summary>
        /// There are no comments for Details1 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string Details1
        {
            get
            {
                string value = _Details1;
                OnGetDetails1(ref value);
                return value;
            }
            set
            {
                if (_Details1 != value)
                {
                  OnDetails1Changing(ref value);
                  ReportPropertyChanging("Details1");
                  _Details1 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("Details1");
                  OnDetails1Changed();
              }
            }
        }
        private string _Details1;
        partial void OnGetDetails1(ref string value);
        partial void OnDetails1Changing(ref string value);
        partial void OnDetails1Changed();
    
        /// <summary>
        /// There are no comments for PRICE in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual global::System.Nullable<decimal> PRICE
        {
            get
            {
                global::System.Nullable<decimal> value = _PRICE;
                OnGetPRICE(ref value);
                return value;
            }
            set
            {
                if (_PRICE != value)
                {
                  OnPRICEChanging(ref value);
                  ReportPropertyChanging("PRICE");
                  _PRICE = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("PRICE");
                  OnPRICEChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _PRICE;
        partial void OnGetPRICE(ref global::System.Nullable<decimal> value);
        partial void OnPRICEChanging(ref global::System.Nullable<decimal> value);
        partial void OnPRICEChanged();
    
        /// <summary>
        /// There are no comments for DUEDATE in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual global::System.Nullable<System.DateTime> DUEDATE
        {
            get
            {
                global::System.Nullable<System.DateTime> value = _DUEDATE;
                OnGetDUEDATE(ref value);
                return value;
            }
            set
            {
                if (_DUEDATE != value)
                {
                  OnDUEDATEChanging(ref value);
                  ReportPropertyChanging("DUEDATE");
                  _DUEDATE = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("DUEDATE");
                  OnDUEDATEChanged();
              }
            }
        }
        private global::System.Nullable<System.DateTime> _DUEDATE;
        partial void OnGetDUEDATE(ref global::System.Nullable<System.DateTime> value);
        partial void OnDUEDATEChanging(ref global::System.Nullable<System.DateTime> value);
        partial void OnDUEDATEChanged();
    
        /// <summary>
        /// There are no comments for SHIPTO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string SHIPTO
        {
            get
            {
                string value = _SHIPTO;
                OnGetSHIPTO(ref value);
                return value;
            }
            set
            {
                if (_SHIPTO != value)
                {
                  OnSHIPTOChanging(ref value);
                  ReportPropertyChanging("SHIPTO");
                  _SHIPTO = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("SHIPTO");
                  OnSHIPTOChanged();
              }
            }
        }
        private string _SHIPTO;
        partial void OnGetSHIPTO(ref string value);
        partial void OnSHIPTOChanging(ref string value);
        partial void OnSHIPTOChanged();
    
        /// <summary>
        /// There are no comments for ADDRESS in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string ADDRESS
        {
            get
            {
                string value = _ADDRESS;
                OnGetADDRESS(ref value);
                return value;
            }
            set
            {
                if (_ADDRESS != value)
                {
                  OnADDRESSChanging(ref value);
                  ReportPropertyChanging("ADDRESS");
                  _ADDRESS = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("ADDRESS");
                  OnADDRESSChanged();
              }
            }
        }
        private string _ADDRESS;
        partial void OnGetADDRESS(ref string value);
        partial void OnADDRESSChanging(ref string value);
        partial void OnADDRESSChanged();
    
        /// <summary>
        /// There are no comments for CustomersPoDocument in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string CustomersPoDocument
        {
            get
            {
                string value = _CustomersPoDocument;
                OnGetCustomersPoDocument(ref value);
                return value;
            }
            set
            {
                if (_CustomersPoDocument != value)
                {
                  OnCustomersPoDocumentChanging(ref value);
                  ReportPropertyChanging("CustomersPoDocument");
                  _CustomersPoDocument = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("CustomersPoDocument");
                  OnCustomersPoDocumentChanged();
              }
            }
        }
        private string _CustomersPoDocument;
        partial void OnGetCustomersPoDocument(ref string value);
        partial void OnCustomersPoDocumentChanging(ref string value);
        partial void OnCustomersPoDocumentChanged();
    
        /// <summary>
        /// There are no comments for CustomersPoDocumentType in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string CustomersPoDocumentType
        {
            get
            {
                string value = _CustomersPoDocumentType;
                OnGetCustomersPoDocumentType(ref value);
                return value;
            }
            set
            {
                if (_CustomersPoDocumentType != value)
                {
                  OnCustomersPoDocumentTypeChanging(ref value);
                  ReportPropertyChanging("CustomersPoDocumentType");
                  _CustomersPoDocumentType = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("CustomersPoDocumentType");
                  OnCustomersPoDocumentTypeChanged();
              }
            }
        }
        private string _CustomersPoDocumentType;
        partial void OnGetCustomersPoDocumentType(ref string value);
        partial void OnCustomersPoDocumentTypeChanging(ref string value);
        partial void OnCustomersPoDocumentTypeChanged();
    
        /// <summary>
        /// There are no comments for Specs in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string Specs
        {
            get
            {
                string value = _Specs;
                OnGetSpecs(ref value);
                return value;
            }
            set
            {
                if (_Specs != value)
                {
                  OnSpecsChanging(ref value);
                  ReportPropertyChanging("Specs");
                  _Specs = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("Specs");
                  OnSpecsChanged();
              }
            }
        }
        private string _Specs;
        partial void OnGetSpecs(ref string value);
        partial void OnSpecsChanging(ref string value);
        partial void OnSpecsChanged();
    
        /// <summary>
        /// There are no comments for Specs1 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string Specs1
        {
            get
            {
                string value = _Specs1;
                OnGetSpecs1(ref value);
                return value;
            }
            set
            {
                if (_Specs1 != value)
                {
                  OnSpecs1Changing(ref value);
                  ReportPropertyChanging("Specs1");
                  _Specs1 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("Specs1");
                  OnSpecs1Changed();
              }
            }
        }
        private string _Specs1;
        partial void OnGetSpecs1(ref string value);
        partial void OnSpecs1Changing(ref string value);
        partial void OnSpecs1Changed();
    
        /// <summary>
        /// There are no comments for PartRevision in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string PartRevision
        {
            get
            {
                string value = _PartRevision;
                OnGetPartRevision(ref value);
                return value;
            }
            set
            {
                if (_PartRevision != value)
                {
                  OnPartRevisionChanging(ref value);
                  ReportPropertyChanging("PartRevision");
                  _PartRevision = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("PartRevision");
                  OnPartRevisionChanged();
              }
            }
        }
        private string _PartRevision;
        partial void OnGetPartRevision(ref string value);
        partial void OnPartRevisionChanging(ref string value);
        partial void OnPartRevisionChanged();

        #endregion
    }

    /// <summary>
    /// There are no comments for CCSpecialModel.PurchaseOrderMaster in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PurchaseOrderMasterID
    /// </KeyProperties>
    [EdmEntityTypeAttribute(NamespaceName="CCSpecialModel", Name="PurchaseOrderMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PurchaseOrderMaster : EntityObject    {
        #region Factory Method

        /// <summary>
        /// Create a new PurchaseOrderMaster object.
        /// </summary>
        /// <param name="purchaseOrderMasterID">Initial value of PurchaseOrderMasterID.</param>
        public static PurchaseOrderMaster CreatePurchaseOrderMaster(string purchaseOrderMasterID)
        {
            PurchaseOrderMaster purchaseOrderMaster = new PurchaseOrderMaster();
            purchaseOrderMaster.PurchaseOrderMasterID = purchaseOrderMasterID;
            return purchaseOrderMaster;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for PurchaseOrderMasterID in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public virtual string PurchaseOrderMasterID
        {
            get
            {
                string value = _PurchaseOrderMasterID;
                OnGetPurchaseOrderMasterID(ref value);
                return value;
            }
            set
            {
                if (_PurchaseOrderMasterID != value)
                {
                  OnPurchaseOrderMasterIDChanging(ref value);
                  ReportPropertyChanging("PurchaseOrderMasterID");
                  _PurchaseOrderMasterID = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("PurchaseOrderMasterID");
                  OnPurchaseOrderMasterIDChanged();
              }
            }
        }
        private string _PurchaseOrderMasterID;
        partial void OnGetPurchaseOrderMasterID(ref string value);
        partial void OnPurchaseOrderMasterIDChanging(ref string value);
        partial void OnPurchaseOrderMasterIDChanged();
    
        /// <summary>
        /// There are no comments for PO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string PO
        {
            get
            {
                string value = _PO;
                OnGetPO(ref value);
                return value;
            }
            set
            {
                if (_PO != value)
                {
                  OnPOChanging(ref value);
                  ReportPropertyChanging("PO");
                  _PO = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("PO");
                  OnPOChanged();
              }
            }
        }
        private string _PO;
        partial void OnGetPO(ref string value);
        partial void OnPOChanging(ref string value);
        partial void OnPOChanged();
    
        /// <summary>
        /// There are no comments for PODATE in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual global::System.Nullable<System.DateTime> PODATE
        {
            get
            {
                global::System.Nullable<System.DateTime> value = _PODATE;
                OnGetPODATE(ref value);
                return value;
            }
            set
            {
                if (_PODATE != value)
                {
                  OnPODATEChanging(ref value);
                  ReportPropertyChanging("PODATE");
                  _PODATE = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("PODATE");
                  OnPODATEChanged();
              }
            }
        }
        private global::System.Nullable<System.DateTime> _PODATE;
        partial void OnGetPODATE(ref global::System.Nullable<System.DateTime> value);
        partial void OnPODATEChanging(ref global::System.Nullable<System.DateTime> value);
        partial void OnPODATEChanged();
    
        /// <summary>
        /// There are no comments for POLINE in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string POLINE
        {
            get
            {
                string value = _POLINE;
                OnGetPOLINE(ref value);
                return value;
            }
            set
            {
                if (_POLINE != value)
                {
                  OnPOLINEChanging(ref value);
                  ReportPropertyChanging("POLINE");
                  _POLINE = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("POLINE");
                  OnPOLINEChanged();
              }
            }
        }
        private string _POLINE;
        partial void OnGetPOLINE(ref string value);
        partial void OnPOLINEChanging(ref string value);
        partial void OnPOLINEChanged();
    
        /// <summary>
        /// There are no comments for PART in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string PART
        {
            get
            {
                string value = _PART;
                OnGetPART(ref value);
                return value;
            }
            set
            {
                if (_PART != value)
                {
                  OnPARTChanging(ref value);
                  ReportPropertyChanging("PART");
                  _PART = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("PART");
                  OnPARTChanged();
              }
            }
        }
        private string _PART;
        partial void OnGetPART(ref string value);
        partial void OnPARTChanging(ref string value);
        partial void OnPARTChanged();
    
        /// <summary>
        /// There are no comments for QTYDUE in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual global::System.Nullable<decimal> QTYDUE
        {
            get
            {
                global::System.Nullable<decimal> value = _QTYDUE;
                OnGetQTYDUE(ref value);
                return value;
            }
            set
            {
                if (_QTYDUE != value)
                {
                  OnQTYDUEChanging(ref value);
                  ReportPropertyChanging("QTYDUE");
                  _QTYDUE = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("QTYDUE");
                  OnQTYDUEChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _QTYDUE;
        partial void OnGetQTYDUE(ref global::System.Nullable<decimal> value);
        partial void OnQTYDUEChanging(ref global::System.Nullable<decimal> value);
        partial void OnQTYDUEChanged();
    
        /// <summary>
        /// There are no comments for DETAILS in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string DETAILS
        {
            get
            {
                string value = _DETAILS;
                OnGetDETAILS(ref value);
                return value;
            }
            set
            {
                if (_DETAILS != value)
                {
                  OnDETAILSChanging(ref value);
                  ReportPropertyChanging("DETAILS");
                  _DETAILS = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("DETAILS");
                  OnDETAILSChanged();
              }
            }
        }
        private string _DETAILS;
        partial void OnGetDETAILS(ref string value);
        partial void OnDETAILSChanging(ref string value);
        partial void OnDETAILSChanged();
    
        /// <summary>
        /// There are no comments for Details1 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string Details1
        {
            get
            {
                string value = _Details1;
                OnGetDetails1(ref value);
                return value;
            }
            set
            {
                if (_Details1 != value)
                {
                  OnDetails1Changing(ref value);
                  ReportPropertyChanging("Details1");
                  _Details1 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("Details1");
                  OnDetails1Changed();
              }
            }
        }
        private string _Details1;
        partial void OnGetDetails1(ref string value);
        partial void OnDetails1Changing(ref string value);
        partial void OnDetails1Changed();
    
        /// <summary>
        /// There are no comments for PRICE in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual global::System.Nullable<decimal> PRICE
        {
            get
            {
                global::System.Nullable<decimal> value = _PRICE;
                OnGetPRICE(ref value);
                return value;
            }
            set
            {
                if (_PRICE != value)
                {
                  OnPRICEChanging(ref value);
                  ReportPropertyChanging("PRICE");
                  _PRICE = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("PRICE");
                  OnPRICEChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _PRICE;
        partial void OnGetPRICE(ref global::System.Nullable<decimal> value);
        partial void OnPRICEChanging(ref global::System.Nullable<decimal> value);
        partial void OnPRICEChanged();
    
        /// <summary>
        /// There are no comments for DUEDATE in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual global::System.Nullable<System.DateTime> DUEDATE
        {
            get
            {
                global::System.Nullable<System.DateTime> value = _DUEDATE;
                OnGetDUEDATE(ref value);
                return value;
            }
            set
            {
                if (_DUEDATE != value)
                {
                  OnDUEDATEChanging(ref value);
                  ReportPropertyChanging("DUEDATE");
                  _DUEDATE = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("DUEDATE");
                  OnDUEDATEChanged();
              }
            }
        }
        private global::System.Nullable<System.DateTime> _DUEDATE;
        partial void OnGetDUEDATE(ref global::System.Nullable<System.DateTime> value);
        partial void OnDUEDATEChanging(ref global::System.Nullable<System.DateTime> value);
        partial void OnDUEDATEChanged();
    
        /// <summary>
        /// There are no comments for SHIPTO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string SHIPTO
        {
            get
            {
                string value = _SHIPTO;
                OnGetSHIPTO(ref value);
                return value;
            }
            set
            {
                if (_SHIPTO != value)
                {
                  OnSHIPTOChanging(ref value);
                  ReportPropertyChanging("SHIPTO");
                  _SHIPTO = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("SHIPTO");
                  OnSHIPTOChanged();
              }
            }
        }
        private string _SHIPTO;
        partial void OnGetSHIPTO(ref string value);
        partial void OnSHIPTOChanging(ref string value);
        partial void OnSHIPTOChanged();
    
        /// <summary>
        /// There are no comments for ADDRESS in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string ADDRESS
        {
            get
            {
                string value = _ADDRESS;
                OnGetADDRESS(ref value);
                return value;
            }
            set
            {
                if (_ADDRESS != value)
                {
                  OnADDRESSChanging(ref value);
                  ReportPropertyChanging("ADDRESS");
                  _ADDRESS = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("ADDRESS");
                  OnADDRESSChanged();
              }
            }
        }
        private string _ADDRESS;
        partial void OnGetADDRESS(ref string value);
        partial void OnADDRESSChanging(ref string value);
        partial void OnADDRESSChanged();
    
        /// <summary>
        /// There are no comments for CustomersPoDocument in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string CustomersPoDocument
        {
            get
            {
                string value = _CustomersPoDocument;
                OnGetCustomersPoDocument(ref value);
                return value;
            }
            set
            {
                if (_CustomersPoDocument != value)
                {
                  OnCustomersPoDocumentChanging(ref value);
                  ReportPropertyChanging("CustomersPoDocument");
                  _CustomersPoDocument = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("CustomersPoDocument");
                  OnCustomersPoDocumentChanged();
              }
            }
        }
        private string _CustomersPoDocument;
        partial void OnGetCustomersPoDocument(ref string value);
        partial void OnCustomersPoDocumentChanging(ref string value);
        partial void OnCustomersPoDocumentChanged();
    
        /// <summary>
        /// There are no comments for CustomersPoDocumentType in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string CustomersPoDocumentType
        {
            get
            {
                string value = _CustomersPoDocumentType;
                OnGetCustomersPoDocumentType(ref value);
                return value;
            }
            set
            {
                if (_CustomersPoDocumentType != value)
                {
                  OnCustomersPoDocumentTypeChanging(ref value);
                  ReportPropertyChanging("CustomersPoDocumentType");
                  _CustomersPoDocumentType = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("CustomersPoDocumentType");
                  OnCustomersPoDocumentTypeChanged();
              }
            }
        }
        private string _CustomersPoDocumentType;
        partial void OnGetCustomersPoDocumentType(ref string value);
        partial void OnCustomersPoDocumentTypeChanging(ref string value);
        partial void OnCustomersPoDocumentTypeChanged();
    
        /// <summary>
        /// There are no comments for Specs in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string Specs
        {
            get
            {
                string value = _Specs;
                OnGetSpecs(ref value);
                return value;
            }
            set
            {
                if (_Specs != value)
                {
                  OnSpecsChanging(ref value);
                  ReportPropertyChanging("Specs");
                  _Specs = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("Specs");
                  OnSpecsChanged();
              }
            }
        }
        private string _Specs;
        partial void OnGetSpecs(ref string value);
        partial void OnSpecsChanging(ref string value);
        partial void OnSpecsChanged();
    
        /// <summary>
        /// There are no comments for Specs1 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string Specs1
        {
            get
            {
                string value = _Specs1;
                OnGetSpecs1(ref value);
                return value;
            }
            set
            {
                if (_Specs1 != value)
                {
                  OnSpecs1Changing(ref value);
                  ReportPropertyChanging("Specs1");
                  _Specs1 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("Specs1");
                  OnSpecs1Changed();
              }
            }
        }
        private string _Specs1;
        partial void OnGetSpecs1(ref string value);
        partial void OnSpecs1Changing(ref string value);
        partial void OnSpecs1Changed();
    
        /// <summary>
        /// There are no comments for PartRevision in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string PartRevision
        {
            get
            {
                string value = _PartRevision;
                OnGetPartRevision(ref value);
                return value;
            }
            set
            {
                if (_PartRevision != value)
                {
                  OnPartRevisionChanging(ref value);
                  ReportPropertyChanging("PartRevision");
                  _PartRevision = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("PartRevision");
                  OnPartRevisionChanged();
              }
            }
        }
        private string _PartRevision;
        partial void OnGetPartRevision(ref string value);
        partial void OnPartRevisionChanging(ref string value);
        partial void OnPartRevisionChanged();
    
        /// <summary>
        /// There are no comments for Terms in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string Terms
        {
            get
            {
                string value = _Terms;
                OnGetTerms(ref value);
                return value;
            }
            set
            {
                if (_Terms != value)
                {
                  OnTermsChanging(ref value);
                  ReportPropertyChanging("Terms");
                  _Terms = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("Terms");
                  OnTermsChanged();
              }
            }
        }
        private string _Terms;
        partial void OnGetTerms(ref string value);
        partial void OnTermsChanging(ref string value);
        partial void OnTermsChanged();
    
        /// <summary>
        /// There are no comments for ShpVia in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string ShpVia
        {
            get
            {
                string value = _ShpVia;
                OnGetShpVia(ref value);
                return value;
            }
            set
            {
                if (_ShpVia != value)
                {
                  OnShpViaChanging(ref value);
                  ReportPropertyChanging("ShpVia");
                  _ShpVia = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("ShpVia");
                  OnShpViaChanged();
              }
            }
        }
        private string _ShpVia;
        partial void OnGetShpVia(ref string value);
        partial void OnShpViaChanging(ref string value);
        partial void OnShpViaChanged();

        #endregion
    }

}
